version: '3'
services:
  proxy:
    build:
      context: ./containers/proxy
    volumes:
      - ./containers/proxy/config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - backend
      - frontend
  backend:
    image: nginx:latest
    volumes:
      - ./backend:/var/www/backend
      - ./containers/backend/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./containers/backend/logs/nginx:/var/log/nginx
    ports:
      - 4040:80
    links:
      - php
      - mailcatcher
  php:
    build:
      context: ./containers/php
    volumes:
      - ./backend:/var/www/backend
    working_dir: /var/www/backend
    user: www-data
    links:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./containers/mysql/mysql-dump:/docker-entrypoint-initdb.d
      - ./containers/mysql/config/docker.cnf:/etc/mysql/conf.d/docker.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/var/www/frontend
      - ./containers/frontend/config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 4000:80
    links:
      - node
  node:
    image: node:8
    volumes:
      - ./frontend:/var/www/frontend
    working_dir: /var/www/frontend
    tty: true

  mailcatcher:
    image: nk/mailcatcher:latest
    ports:
      - 1080:80
  redis_cache:
    image: redis:5.0.5-alpine
  redis_session:
    image: redis:5.0.5-alpine

  mercure:
    image: dunglas/mercure:latest
    environment:
      JWT_KEY: "secret"
      ALLOW_ANONYMOUS: "1"
      CORS_ALLOWED_ORIGINS: "https://adventure-local.divante.pl"
      PUBLISH_ALLOWED_ORIGINS: "*"
      DEBUG: "1"
    links:
      - backend
      - frontend
