<?php

namespace Adventure\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20200415045525 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE leave_period DROP FOREIGN KEY fk_employee_leave_period');
        $this->addSql('ALTER TABLE leave_period ADD CONSTRAINT FK_F37E80618C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE leave_period RENAME INDEX fk_leave_period_employee TO IDX_F37E80618C03F15C');
        $this->addSql('ALTER TABLE employee_skill_history DROP FOREIGN KEY FK_employee_skill_history_employee');
        $this->addSql('ALTER TABLE employee_skill_history DROP FOREIGN KEY FK_employee_skill_history_skill');
        $this->addSql('ALTER TABLE employee_skill_history ADD CONSTRAINT FK_4BBD9AD95585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_skill_history ADD CONSTRAINT FK_4BBD9AD98C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_agreement DROP FOREIGN KEY FK_employee_agreement_agreement');
        $this->addSql('ALTER TABLE employee_agreement DROP FOREIGN KEY FK_employee_agreement_employee');
        $this->addSql('DROP INDEX employee_id_agreement_id ON employee_agreement');
        $this->addSql('ALTER TABLE employee_agreement ADD CONSTRAINT FK_2BF532668C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_agreement ADD CONSTRAINT FK_2BF5326624890B2B FOREIGN KEY (agreement_id) REFERENCES agreement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill DROP FOREIGN KEY FK_skill_employee');
        $this->addSql('ALTER TABLE skill DROP FOREIGN KEY FK_skill_skill_area');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT FK_5E3DE477A7FADEB5 FOREIGN KEY (skill_area_id) REFERENCES skill_area (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT FK_5E3DE4778C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE level DROP FOREIGN KEY FK_9AEACC13D5CAD932');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC13D5CAD932 FOREIGN KEY (strategy_id) REFERENCES leveling_strategy (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE position DROP FOREIGN KEY FK_462CE4F5D5CAD932');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F5D5CAD932 FOREIGN KEY (strategy_id) REFERENCES leveling_strategy (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evidence_invoice_attachment DROP FOREIGN KEY FK_1566BC788AE72EDA');
        $this->addSql('ALTER TABLE evidence_invoice_attachment ADD CONSTRAINT FK_1566BC788AE72EDA FOREIGN KEY (owner_employee_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee DROP FOREIGN KEY FK_5D9F75A12576E0FD');
        $this->addSql('ALTER TABLE employee DROP FOREIGN KEY FK_5D9F75A15FB14BA7');
        $this->addSql('ALTER TABLE employee DROP FOREIGN KEY FK_5D9F75A16F3EE0AD');
        $this->addSql('ALTER TABLE employee DROP FOREIGN KEY FK_5D9F75A1DD842E46');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A12576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A15FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A16F3EE0AD FOREIGN KEY (tribe_id) REFERENCES tribe (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A1DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE agreement_attachment_download_token DROP FOREIGN KEY FK_ED3F329F464E68B');
        $this->addSql('ALTER TABLE agreement_attachment_download_token ADD CONSTRAINT FK_ED3F329F464E68B FOREIGN KEY (attachment_id) REFERENCES attachment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_skill_area DROP FOREIGN KEY FK__project');
        $this->addSql('ALTER TABLE project_skill_area DROP FOREIGN KEY FK_project_skill_area_skill_area');
        $this->addSql('ALTER TABLE project_skill_area ADD CONSTRAINT FK_8873DAE8A7FADEB5 FOREIGN KEY (skill_area_id) REFERENCES skill_area (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_skill_area ADD CONSTRAINT FK_8873DAE8166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_hardware DROP FOREIGN KEY FK_6EA6B82789EFB0AC');
        $this->addSql('ALTER TABLE employee_hardware DROP FOREIGN KEY FK_6EA6B8278C03F15C');
        $this->addSql('ALTER TABLE employee_hardware ADD CONSTRAINT FK_6EA6B82789EFB0AC FOREIGN KEY (potential_employee_id) REFERENCES potential_employee (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE employee_hardware ADD CONSTRAINT FK_6EA6B8278C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE employee_skill DROP FOREIGN KEY FK__skill');
        $this->addSql('ALTER TABLE employee_skill DROP FOREIGN KEY FK_employee_skill_employee');
        $this->addSql('ALTER TABLE employee_skill ADD CONSTRAINT FK_B630E90E8C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_skill ADD CONSTRAINT FK_B630E90E5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_skill ADD CONSTRAINT FK_B630E90EA7FADEB5 FOREIGN KEY (skill_area_id) REFERENCES skill_area (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_B630E90EA7FADEB5 ON employee_skill (skill_area_id)');
        $this->addSql('ALTER TABLE checklist_question DROP FOREIGN KEY FK_EBF3358C602AD315');
        $this->addSql('ALTER TABLE checklist_question DROP FOREIGN KEY FK_EBF3358CB16D08A7');
        $this->addSql('ALTER TABLE checklist_question ADD CONSTRAINT FK_EBF3358C602AD315 FOREIGN KEY (responsible_id) REFERENCES employee (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE checklist_question ADD CONSTRAINT FK_EBF3358CB16D08A7 FOREIGN KEY (checklist_id) REFERENCES checklist (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE checklist DROP FOREIGN KEY FK_5C696D2F23EDC87');
        $this->addSql('ALTER TABLE checklist DROP FOREIGN KEY FK_5C696D2F7E3C61F9');
        $this->addSql('ALTER TABLE checklist ADD CONSTRAINT FK_5C696D2F23EDC87 FOREIGN KEY (subject_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE checklist ADD CONSTRAINT FK_5C696D2F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES employee (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE checklist_template_question DROP FOREIGN KEY FK_C030E916602AD315');
        $this->addSql('ALTER TABLE checklist_template_question DROP FOREIGN KEY FK_C030E916B16D08A7');
        $this->addSql('ALTER TABLE checklist_template_question ADD CONSTRAINT FK_C030E916602AD315 FOREIGN KEY (responsible_id) REFERENCES employee (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE checklist_template_question ADD CONSTRAINT FK_C030E916B16D08A7 FOREIGN KEY (checklist_id) REFERENCES checklist_template (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE potential_employee DROP FOREIGN KEY FK_26DD2863156BE243');
        $this->addSql('ALTER TABLE potential_employee DROP FOREIGN KEY FK_26DD286331AACC7');
        $this->addSql('ALTER TABLE potential_employee DROP FOREIGN KEY FK_26DD28639C02A8D5');
        $this->addSql('ALTER TABLE potential_employee DROP FOREIGN KEY FK_26DD2863BCE1E7BB');
        $this->addSql('ALTER TABLE potential_employee ADD CONSTRAINT FK_26DD2863156BE243 FOREIGN KEY (recruiter_id) REFERENCES employee (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE potential_employee ADD CONSTRAINT FK_26DD286331AACC7 FOREIGN KEY (joined_employee_id) REFERENCES employee (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE potential_employee ADD CONSTRAINT FK_26DD28639C02A8D5 FOREIGN KEY (designated_position_id) REFERENCES position (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE potential_employee ADD CONSTRAINT FK_26DD2863BCE1E7BB FOREIGN KEY (designated_tribe_id) REFERENCES tribe (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE news DROP FOREIGN KEY FK_1DD39950F675F31B');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT FK_1DD39950F675F31B FOREIGN KEY (author_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_skill_area DROP FOREIGN KEY FK__employee');
        $this->addSql('ALTER TABLE employee_skill_area DROP FOREIGN KEY FK__skill_area');
        $this->addSql('ALTER TABLE employee_skill_area ADD CONSTRAINT FK_802110EA7FADEB5 FOREIGN KEY (skill_area_id) REFERENCES skill_area (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_skill_area ADD CONSTRAINT FK_802110E8C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE leave_request_day ADD CONSTRAINT FK_9B5C8D8BEC8B7ADE FOREIGN KEY (period_id) REFERENCES leave_period (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE leave_request_day ADD CONSTRAINT FK_9B5C8D8B8C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_9B5C8D8BEC8B7ADE ON leave_request_day (period_id)');
        $this->addSql('CREATE INDEX IDX_9B5C8D8B8C03F15C ON leave_request_day (employee_id)');
        $this->addSql('ALTER TABLE agreement_contract DROP FOREIGN KEY FK_389C569C24890B2B');
        $this->addSql('ALTER TABLE agreement_contract DROP FOREIGN KEY FK_389C569C2576E0FD');
        $this->addSql('ALTER TABLE agreement_contract ADD CONSTRAINT FK_389C569C24890B2B FOREIGN KEY (agreement_id) REFERENCES agreement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE agreement_contract ADD CONSTRAINT FK_389C569C2576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_occupancy DROP FOREIGN KEY FK_809E38B4166D1F9C');
        $this->addSql('ALTER TABLE employee_occupancy DROP FOREIGN KEY FK_809E38B48C03F15C');
        $this->addSql('ALTER TABLE employee_occupancy ADD CONSTRAINT FK_809E38B4166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_occupancy ADD CONSTRAINT FK_809E38B48C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE links DROP FOREIGN KEY FK_D182A118F675F31B');
        $this->addSql('ALTER TABLE links ADD CONSTRAINT FK_D182A118F675F31B FOREIGN KEY (author_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sick_leave_attachment DROP FOREIGN KEY FK_sick_leave_attachment3_employee');
        $this->addSql('ALTER TABLE sick_leave_attachment ADD CONSTRAINT FK_BE47A3A58C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sick_leave_attachment RENAME INDEX fk_sick_leave_attachment3_employee TO IDX_BE47A3A58C03F15C');
        $this->addSql('ALTER TABLE sick_leave_attachment_download_token DROP FOREIGN KEY FK_36A6AF4E464E68B');
        $this->addSql('ALTER TABLE sick_leave_attachment_download_token ADD CONSTRAINT FK_36A6AF4E464E68B FOREIGN KEY (attachment_id) REFERENCES sick_leave_attachment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_project DROP FOREIGN KEY FK_employee_project_employee');
        $this->addSql('ALTER TABLE employee_project DROP FOREIGN KEY FK_employee_project_project');
        $this->addSql('ALTER TABLE employee_project ADD CONSTRAINT FK_AFFF86E1166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_project ADD CONSTRAINT FK_AFFF86E18C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evidence_overtime DROP FOREIGN KEY FK_F14A9894B528FC11');
        $this->addSql('ALTER TABLE evidence_overtime ADD CONSTRAINT FK_F14A9894B528FC11 FOREIGN KEY (evidence_id) REFERENCES evidence (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE leave_request DROP FOREIGN KEY FK_employee_leave_request_employee_1');
        $this->addSql('ALTER TABLE leave_request ADD CONSTRAINT FK_7DC8F778783E3463 FOREIGN KEY (manager_id) REFERENCES employee (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE leave_request RENAME INDEX idx_leave_request_period_id TO FK_leave_request_employee_leave_period');
        $this->addSql('ALTER TABLE leave_request RENAME INDEX idx_leave_request_manager_id TO FK_leave_request_employee_2');
        $this->addSql('ALTER TABLE sick_leave_request_attachment RENAME INDEX fk_sick_leave_request_attachment3_attachment TO IDX_A43F0640D460611C');
        $this->addSql('ALTER TABLE evidence DROP FOREIGN KEY FK_C615710783E3463');
        $this->addSql('ALTER TABLE evidence DROP FOREIGN KEY FK_C6157108C03F15C');
        $this->addSql('ALTER TABLE evidence ADD CONSTRAINT FK_C615710783E3463 FOREIGN KEY (manager_id) REFERENCES employee (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE evidence ADD CONSTRAINT FK_C6157108C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema) : void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');
        $this->addSql('ALTER TABLE agreement_attachment_download_token DROP FOREIGN KEY FK_ED3F329F464E68B');
        $this->addSql('ALTER TABLE agreement_attachment_download_token ADD CONSTRAINT FK_ED3F329F464E68B FOREIGN KEY (attachment_id) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE agreement_contract DROP FOREIGN KEY FK_389C569C24890B2B');
        $this->addSql('ALTER TABLE agreement_contract DROP FOREIGN KEY FK_389C569C2576E0FD');
        $this->addSql('ALTER TABLE agreement_contract ADD CONSTRAINT FK_389C569C24890B2B FOREIGN KEY (agreement_id) REFERENCES agreement (id)');
        $this->addSql('ALTER TABLE agreement_contract ADD CONSTRAINT FK_389C569C2576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id)');
        $this->addSql('ALTER TABLE checklist DROP FOREIGN KEY FK_5C696D2F7E3C61F9');
        $this->addSql('ALTER TABLE checklist DROP FOREIGN KEY FK_5C696D2F23EDC87');
        $this->addSql('ALTER TABLE checklist ADD CONSTRAINT FK_5C696D2F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE checklist ADD CONSTRAINT FK_5C696D2F23EDC87 FOREIGN KEY (subject_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE checklist_question DROP FOREIGN KEY FK_EBF3358CB16D08A7');
        $this->addSql('ALTER TABLE checklist_question DROP FOREIGN KEY FK_EBF3358C602AD315');
        $this->addSql('ALTER TABLE checklist_question ADD CONSTRAINT FK_EBF3358CB16D08A7 FOREIGN KEY (checklist_id) REFERENCES checklist (id)');
        $this->addSql('ALTER TABLE checklist_question ADD CONSTRAINT FK_EBF3358C602AD315 FOREIGN KEY (responsible_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE checklist_template_question DROP FOREIGN KEY FK_C030E916B16D08A7');
        $this->addSql('ALTER TABLE checklist_template_question DROP FOREIGN KEY FK_C030E916602AD315');
        $this->addSql('ALTER TABLE checklist_template_question ADD CONSTRAINT FK_C030E916B16D08A7 FOREIGN KEY (checklist_id) REFERENCES checklist_template (id)');
        $this->addSql('ALTER TABLE checklist_template_question ADD CONSTRAINT FK_C030E916602AD315 FOREIGN KEY (responsible_id) REFERENCES employee (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1AA881CE5E237E06 ON data_processing_criterium (name_pl)');
        $this->addSql('ALTER TABLE employee DROP FOREIGN KEY FK_5D9F75A16F3EE0AD');
        $this->addSql('ALTER TABLE employee DROP FOREIGN KEY FK_5D9F75A1DD842E46');
        $this->addSql('ALTER TABLE employee DROP FOREIGN KEY FK_5D9F75A15FB14BA7');
        $this->addSql('ALTER TABLE employee DROP FOREIGN KEY FK_5D9F75A12576E0FD');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A16F3EE0AD FOREIGN KEY (tribe_id) REFERENCES tribe (id)');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A1DD842E46 FOREIGN KEY (position_id) REFERENCES position (id)');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A15FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id)');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A12576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id)');
        $this->addSql('ALTER TABLE employee_agreement DROP FOREIGN KEY FK_2BF532668C03F15C');
        $this->addSql('ALTER TABLE employee_agreement DROP FOREIGN KEY FK_2BF5326624890B2B');
        $this->addSql('ALTER TABLE employee_agreement ADD CONSTRAINT FK_employee_agreement_agreement FOREIGN KEY (agreement_id) REFERENCES agreement (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_agreement ADD CONSTRAINT FK_employee_agreement_employee FOREIGN KEY (employee_id) REFERENCES employee (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_2BF532668C03F15C ON employee_agreement (employee_id)');
        $this->addSql('CREATE UNIQUE INDEX employee_id_agreement_id ON employee_agreement (employee_id, agreement_id)');
        $this->addSql('ALTER TABLE employee_hardware DROP FOREIGN KEY FK_6EA6B8278C03F15C');
        $this->addSql('ALTER TABLE employee_hardware DROP FOREIGN KEY FK_6EA6B82789EFB0AC');
        $this->addSql('ALTER TABLE employee_hardware ADD CONSTRAINT FK_6EA6B8278C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE employee_hardware ADD CONSTRAINT FK_6EA6B82789EFB0AC FOREIGN KEY (potential_employee_id) REFERENCES potential_employee (id)');
        $this->addSql('ALTER TABLE employee_occupancy DROP FOREIGN KEY FK_809E38B48C03F15C');
        $this->addSql('ALTER TABLE employee_occupancy DROP FOREIGN KEY FK_809E38B4166D1F9C');
        $this->addSql('ALTER TABLE employee_occupancy ADD CONSTRAINT FK_809E38B48C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE employee_occupancy ADD CONSTRAINT FK_809E38B4166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE employee_project DROP FOREIGN KEY FK_AFFF86E1166D1F9C');
        $this->addSql('ALTER TABLE employee_project DROP FOREIGN KEY FK_AFFF86E18C03F15C');
        $this->addSql('ALTER TABLE employee_project ADD CONSTRAINT FK_employee_project_employee FOREIGN KEY (employee_id) REFERENCES employee (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_project ADD CONSTRAINT FK_employee_project_project FOREIGN KEY (project_id) REFERENCES project (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_skill DROP FOREIGN KEY FK_B630E90E8C03F15C');
        $this->addSql('ALTER TABLE employee_skill DROP FOREIGN KEY FK_B630E90E5585C142');
        $this->addSql('ALTER TABLE employee_skill DROP FOREIGN KEY FK_B630E90EA7FADEB5');
        $this->addSql('DROP INDEX IDX_B630E90EA7FADEB5 ON employee_skill');
        $this->addSql('ALTER TABLE employee_skill ADD CONSTRAINT FK__skill FOREIGN KEY (skill_id) REFERENCES skill (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_skill ADD CONSTRAINT FK_employee_skill_employee FOREIGN KEY (employee_id) REFERENCES employee (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_skill_area DROP FOREIGN KEY FK_802110EA7FADEB5');
        $this->addSql('ALTER TABLE employee_skill_area DROP FOREIGN KEY FK_802110E8C03F15C');
        $this->addSql('ALTER TABLE employee_skill_area ADD CONSTRAINT FK__employee FOREIGN KEY (employee_id) REFERENCES employee (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_skill_area ADD CONSTRAINT FK__skill_area FOREIGN KEY (skill_area_id) REFERENCES skill_area (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_skill_history DROP FOREIGN KEY FK_4BBD9AD95585C142');
        $this->addSql('ALTER TABLE employee_skill_history DROP FOREIGN KEY FK_4BBD9AD98C03F15C');
        $this->addSql('ALTER TABLE employee_skill_history ADD CONSTRAINT FK_employee_skill_history_employee FOREIGN KEY (employee_id) REFERENCES employee (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_skill_history ADD CONSTRAINT FK_employee_skill_history_skill FOREIGN KEY (skill_id) REFERENCES skill (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evidence DROP FOREIGN KEY FK_C6157108C03F15C');
        $this->addSql('ALTER TABLE evidence DROP FOREIGN KEY FK_C615710783E3463');
        $this->addSql('ALTER TABLE evidence ADD CONSTRAINT FK_C6157108C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE evidence ADD CONSTRAINT FK_C615710783E3463 FOREIGN KEY (manager_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE evidence_invoice_attachment DROP FOREIGN KEY FK_1566BC788AE72EDA');
        $this->addSql('ALTER TABLE evidence_invoice_attachment ADD CONSTRAINT FK_1566BC788AE72EDA FOREIGN KEY (owner_employee_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE evidence_overtime DROP FOREIGN KEY FK_F14A9894B528FC11');
        $this->addSql('ALTER TABLE evidence_overtime ADD CONSTRAINT FK_F14A9894B528FC11 FOREIGN KEY (evidence_id) REFERENCES evidence (id)');
        $this->addSql('ALTER TABLE leave_period DROP FOREIGN KEY FK_F37E80618C03F15C');
        $this->addSql('ALTER TABLE leave_period ADD CONSTRAINT fk_employee_leave_period FOREIGN KEY (employee_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE leave_period RENAME INDEX idx_f37e80618c03f15c TO FK_leave_period_employee');
        $this->addSql('ALTER TABLE leave_request DROP FOREIGN KEY FK_7DC8F778783E3463');
        $this->addSql('ALTER TABLE leave_request ADD CONSTRAINT FK_employee_leave_request_employee_1 FOREIGN KEY (manager_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE leave_request RENAME INDEX fk_leave_request_employee_leave_period TO IDX_leave_request_period_id');
        $this->addSql('ALTER TABLE leave_request RENAME INDEX fk_leave_request_employee_2 TO IDX_leave_request_manager_id');
        $this->addSql('ALTER TABLE leave_request_day DROP FOREIGN KEY FK_9B5C8D8BEC8B7ADE');
        $this->addSql('ALTER TABLE leave_request_day DROP FOREIGN KEY FK_9B5C8D8B8C03F15C');
        $this->addSql('DROP INDEX IDX_9B5C8D8BEC8B7ADE ON leave_request_day');
        $this->addSql('DROP INDEX IDX_9B5C8D8B8C03F15C ON leave_request_day');
        $this->addSql('ALTER TABLE level DROP FOREIGN KEY FK_9AEACC13D5CAD932');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC13D5CAD932 FOREIGN KEY (strategy_id) REFERENCES leveling_strategy (id)');
        $this->addSql('ALTER TABLE links DROP FOREIGN KEY FK_D182A118F675F31B');
        $this->addSql('ALTER TABLE links ADD CONSTRAINT FK_D182A118F675F31B FOREIGN KEY (author_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE news DROP FOREIGN KEY FK_1DD39950F675F31B');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT FK_1DD39950F675F31B FOREIGN KEY (author_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE position DROP FOREIGN KEY FK_462CE4F5D5CAD932');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F5D5CAD932 FOREIGN KEY (strategy_id) REFERENCES leveling_strategy (id)');
        $this->addSql('ALTER TABLE potential_employee DROP FOREIGN KEY FK_26DD2863BCE1E7BB');
        $this->addSql('ALTER TABLE potential_employee DROP FOREIGN KEY FK_26DD28639C02A8D5');
        $this->addSql('ALTER TABLE potential_employee DROP FOREIGN KEY FK_26DD286331AACC7');
        $this->addSql('ALTER TABLE potential_employee DROP FOREIGN KEY FK_26DD2863156BE243');
        $this->addSql('ALTER TABLE potential_employee ADD CONSTRAINT FK_26DD2863BCE1E7BB FOREIGN KEY (designated_tribe_id) REFERENCES tribe (id)');
        $this->addSql('ALTER TABLE potential_employee ADD CONSTRAINT FK_26DD28639C02A8D5 FOREIGN KEY (designated_position_id) REFERENCES position (id)');
        $this->addSql('ALTER TABLE potential_employee ADD CONSTRAINT FK_26DD286331AACC7 FOREIGN KEY (joined_employee_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE potential_employee ADD CONSTRAINT FK_26DD2863156BE243 FOREIGN KEY (recruiter_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE project_skill_area DROP FOREIGN KEY FK_8873DAE8A7FADEB5');
        $this->addSql('ALTER TABLE project_skill_area DROP FOREIGN KEY FK_8873DAE8166D1F9C');
        $this->addSql('ALTER TABLE project_skill_area ADD CONSTRAINT FK__project FOREIGN KEY (project_id) REFERENCES project (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_skill_area ADD CONSTRAINT FK_project_skill_area_skill_area FOREIGN KEY (skill_area_id) REFERENCES skill_area (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sick_leave_attachment DROP FOREIGN KEY FK_BE47A3A58C03F15C');
        $this->addSql('ALTER TABLE sick_leave_attachment ADD CONSTRAINT FK_sick_leave_attachment3_employee FOREIGN KEY (employee_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE sick_leave_attachment RENAME INDEX idx_be47a3a58c03f15c TO FK_sick_leave_attachment3_employee');
        $this->addSql('ALTER TABLE sick_leave_attachment_download_token DROP FOREIGN KEY FK_36A6AF4E464E68B');
        $this->addSql('ALTER TABLE sick_leave_attachment_download_token ADD CONSTRAINT FK_36A6AF4E464E68B FOREIGN KEY (attachment_id) REFERENCES sick_leave_attachment (id)');
        $this->addSql('ALTER TABLE sick_leave_request_attachment RENAME INDEX idx_a43f0640d460611c TO FK_sick_leave_request_attachment3_attachment');
        $this->addSql('ALTER TABLE skill DROP FOREIGN KEY FK_5E3DE477A7FADEB5');
        $this->addSql('ALTER TABLE skill DROP FOREIGN KEY FK_5E3DE4778C03F15C');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT FK_skill_employee FOREIGN KEY (employee_id) REFERENCES employee (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT FK_skill_skill_area FOREIGN KEY (skill_area_id) REFERENCES skill_area (id) ON UPDATE CASCADE ON DELETE CASCADE');
    }
}
